### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by MeycL** [Xiaolong-Liu-bdsc/IGRec#1]
Thank you very much for your excellent work. It seems that the dataset provided only includes Steam. Could you please provide MaFengWo and Douban datasets as well? Thank you very much.

**Comment by Xiaolong-Liu-bdsc** [comment]
Two datasets are uploaded into Drive.

**Comment by MeycL** [comment]
Thank you very much for your prompt reply. I would like to express my gratitude once again for open-sourcing the dataset.
